### ISSUE TITLE
How to call the module

### ISSUE THREAD

**Issue by Abdouflih** [br34th3r/PythonLoginAndRegister#1]
i tried to import PythonLoginAndRegister
But didnt work
What to import?

**Comment by GGontijo** [comment]
You can import with "from src import LogAndReg",
and then use with "user = LogAndReg.createUser('name', 'surname', 'email', 'password')"

I guess the pip installed package is in a wrong fold structure, because all the installed packages has 2 folders:

"SomePipInstalledPackage" and "SomePipInstalledPackage-VersionInfo-info"

But this has only "PythonLoginAndRegister-version-info" folder, the core code is directly in "src" and it's not initialized with an __init__.py file (Python recognize dirs with this file as a importable package), this does not break the import itself but some code editor (like vscode, that i use) does not recognizes them..

**Comment by GGontijo** [comment]
To add more information, if someone want to fix this..

package structure now (C:\users\USER\appdata\local\programs\python\python310\lib\site-packages\):
![image](https://user-images.githubusercontent.com/38219914/190474245-82839208-a474-4fc8-81be-7f545949468d.png)

What i think it's needed to be:
![image](https://user-images.githubusercontent.com/38219914/190474547-6ec84e1a-fbbb-497b-8aac-9612a10a5869.png)

**Comment by GGontijo** [comment]
Created a PR to solve this :D 

https://github.com/br34th3r/PythonLoginAndRegister/pull/2

**Comment by br34th3r** [comment]
Thanks for this, I really haven't been maintaining this project very well in all honesty so appreciate the PR you put through. It's just been merged! I'll close this issue now as it should be an ample solution!
